### ISSUE TITLE
unable to build commerce 

### ISSUE THREAD

**Issue by vnaz** [ottemo/foundation#506]
ref to https://github.com/ottemo/dashboard/issues/370

**Comment by vastbinderj** [comment]
@vnaz I don't see how the commits in the PR fix the problem where one cannot log in with the default admin credentials when they first start commerce on a fresh database?

Now that I think of it, I'll try later when I have a few minutes to build this branch start up commerce.

**Comment by vnaz** [comment]
I can't see PR for login issue, I've published the build issues fix when you downloading the package and it does not want to build

**Comment by vastbinderj** [comment]
ok - renamed the issue

**Comment by vastbinderj** [comment]
closed and fixed by ottemo/commerce#507
