### ISSUE TITLE
Thumbs error

### ISSUE THREAD

**Issue by coldestheart** [ottemo/foundation#512]
thumbs always return 
> _id | "5d3424670ef414ad18922027"
> default_image | "3_1563700365.jpg"
> description | "asda"
> enabled | true
> images |  
> 0 |  
> thumb | "media/image/Product/5d3424670ef414ad18922027/3_1563700365_280x350.jpg"

**But default folder in .ini file is "static" not media.**

**Comment by vnaz** [comment]
please check the 'general.app.media_base_url' vale in 'config' table

**Comment by coldestheart** [comment]
Thanks it helps!
